### ISSUE TITLE
arkdb requires R (>= 3.5.0)

### ISSUE THREAD

**Issue by spkaluzny** [ropensci/arkdb#17]
arkdb (Version 0.0.2) cannot be installed from source in R-3.4.4 under Linux, it requires the utils::askYesNo function which was added to R-3.5.0.

    version$version.string
    #> [1] "R version 3.4.4 (2018-03-15)"
    install.packages("arkdb")
    #> Installing package into ‘/home/R/site-library_R-3.4’
    #> (as ‘lib’ is unspecified)
    #> trying URL 'http://erratic/cran/src/contrib/arkdb_0.0.2.tar.gz'
    #> Content type 'application/x-gzip' length 27979 bytes (27 KB)
    #> ==================================================
    #> downloaded 27 KB
    #>
    #> * installing *source* package ‘arkdb’ ...
    #> ** package ‘arkdb’ successfully unpacked and MD5 sums checked
    #> ** R
    #> ** inst
    #> ** byte-compile and prepare package for lazy loading
    #> Error : object ‘askYesNo’ is not exported by 'namespace:utils'
    #> ERROR: lazy loading failed for package ‘arkdb’
    #> * removing ‘/home/R/site-library_R-3.4/arkdb’

**Comment by cboettig** [comment]
Fixed to be backwards compatible. release coming soon, thanks again for reporting this
