### ISSUE TITLE
Set readr method's  default column type to `character`?

### ISSUE THREAD

**Issue by cboettig** [ropensci/arkdb#29]
`readr` uses `logical` as the default column type when the first `n=1000` lines are all `NA`. (The reason for this is to play nicely with operations like `bind_rows()`, since you can upcast a logical `NA` to a character `NA` but not vice versa, see https://github.com/tidyverse/readr/issues/839.   (base `read.csv` also defaults NAs to logical).  

In general I still feel this is the wrong default, as it allows R to make a guess in data parsing that is somewhat destructive:  sparsely filled text columns become coerced to all NA because it has text cannot be coerced into a logical.  It would probably be safer to default this to character and allow the text and not destroy data.

It seems like it would have been preferable to change the casting behavior used in `dplyr` to allow it to cast/bind the all-NA character columns?

cc @noamross

**Comment by noamross** [comment]
I've got good arguments on both sides, and ultimately figure that this will bite the user either way. It's easy to construct a situation where either behavior breaks inputs.  Not that helpful a comment, I guess  ¯\_(ツ)_/¯ .

**Comment by cboettig** [comment]
meh, we've with `readr`'s own defaults since it's easy to overwrite by passing ` col_types = readr::cols(.default = "c"))` (or `colClasses = "character"` with the base methods)

nevertheless just about every time I import a large data file from some area of ecology I find text converted to NA because `readr` decided the first 1000 NAs meant it should be a logical.  I find getting text data wiped out to `NA` is both harder to spot and harder to fix than having a logical turned into text, and text format for a text file sounds like a safer choice.  Further, many random text files often encode logicals as integers or etc that aren't automatically parsed as logicals anyway so we have to explicitly type or coerce them.  anyway, /rant since that's neither here nor there...
