### ISSUE TITLE
Handling column types robustly

### ISSUE THREAD

**Issue by noamross** [ropensci/arkdb#39]
It would be good to be able to robustly save and restore column types in a predictable fashion.  Data with large numbers of NAs tends to have issues with errors detecting column types correctly, and certain types, such as dates, are not retained.

Would it make sense to create an option to create and/or use a file like `schema.json` to set data types?

One enabling change for this is to allow arguments to be passed to the native bulk importers (which generally use `read.csv` and `colClasses` to set up column types to create tables before importing). 

cc @emmamendelsohn

**Comment by cboettig** [comment]
yeah, definitely.  Note that you already should be able to pass arbitrary arguments to the read methods, e.g.

https://github.com/ropensci/taxadb/blob/abc855e2a8e1b2b864419b28a2293da680a88688/R/td_create.R#L84

I think that includes bulk importers but maybe it doesn't?  Definitely necessary to be able to set this manually, e.g. whenever importing large tabular files (GBIF, BioTime, etc) that weren't created by arkdb.  


Creating a `schema.json` metadata file with basic column types automatically on `arkdb::ark()` would be awesome though.  I believe schema.org terms are rich enough to cover at least atomic types (int, double, boolean, string, maybe date/time), and we won't worry about factors/ordered factors or more complex types?

Arguably this has always been a reason to use a format that encodes type, and maybe we need better support for that.  (JSON is a nice text-based standard with native typing of boolean, string, and numeric at least, though not very efficient to parse for tabular data!  fst is an obvious one, though kinda feels like parquet is the natural solution here.  Of course good ol csv will be more user friendly than parquet for archiving for some time to come, so I guess `schema.json` it is!).

**Comment by noamross** [comment]
Here is where we would add the ability to pass arguments to the bulk importers. I believe both MonetDB and duckdb use `colClasses`: https://github.com/ropensci/arkdb/blob/master/R/bulk_importers.R#L70

I could imagine parquet files being an option down the road, but agree for now we should stick with text-based formats.

**Comment by cboettig** [comment]
:+1: PR's welcome!

**Comment by noamross** [comment]
Oh yeah this is definitely mostly a note for myself.

**Comment by GitHunter0** [comment]
The most troublesome for me has been the consistent loss of the `date` format

**Comment by cboettig** [comment]
@GitHunter0 parquet is a great alternative to serialize while preserving schema & type.  Now supported here and in `duckdb`

**Comment by GitHunter0** [comment]
@cboettig , great to know! 
Could you provide an example of how to use `ark()` and `unark()` using `parquet` format instead of `.tsv.bz2`

**Comment by cboettig** [comment]
just use `streamable_parquet()`, there's an example in the README https://github.com/ropensci/arkdb#ark-in-parallel (somewhat cryptically that example focuses on it being done in parallel, which is great and all, but happens to also show the use of parquet)

**Comment by cboettig** [comment]
(fwiw, also just check out `arrow::open_dataset()` and arrow::write_dataset()`.  In many cases this does more-or-less the same `arkdb` does, but with loads of additional benefits in performance, hive partitioning, etc.  arkdb may still be useful for running data into and out of existing relational DBs, but generally for larger-than-RAM serializations and queries arrow is a brilliant, highly professional and highly optimized option...

**Comment by cboettig** [comment]
Good question! @1beb we don't seem to have any unit test for `unark` using streamable_parquet?

**Comment by GitHunter0** [comment]
I would love to see this working. @cboettig , @1beb , would you folks consider reopening the issue until a solution is validated?

**Comment by GitHunter0** [comment]
Hey @cboettig , thanks for the response. It should be it, however I still cannot make it work, I'm trying this code:
```
  dir = "data/temp"
  table = "original_table"
  
  arkdb::ark(
    db_con = db_con, 
    dir = .dir, 
    streamable_table = arkdb::streamable_parquet(),
    tables = table,  
    overwrite = TRUE
  )
  
  files <- 
    list.files(glue("{dir}/{table}"), pattern = "parquet", full.names = T) 
  
  arkdb::unark(
    files = files,
    db_con = db_con,
    streamable_table = arkdb::streamable_parquet(),
    tablenames = "new_table",
    overwrite = TRUE
  )   
```

And receiving this weird error message:
```
Importing data/temp/original_table/part-00001.parquet in 50000 line chunks:
Error: IOError: Failed to open local file 'PAR1L
$

P1-02-03

2022-03-04
2020-01-01
$
2022-03-04
2020-01-01
$
$
5
<

5
$
%duble
%bool_int
2022-03-04
2020-01-01
5
<

5
3
262657
197888
5
UTF-8
531
2
531
1
16
1
262153
10
data.frame
1026
1
262153
5
names
16
1
262153
5
class
254
531
7
254
254
254
254
254
254
254
1026
511
16
7
262153
2
id
262153
8
date_str
262153
3
int
262153
5
duble
262153
4
bool
262153
8
bool_int
262153
4
date
254
1026
511
16
2
262153
10
attributes
262153
7
columns
254

'. Detail: [Windows error 3] The system cannot find the path specified.
```
For some reason it can't find the path.

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

other attached packages:
[1] arkdb_0.0.16
```

**Comment by 1beb** [comment]
What I see here looks like what I would get if I tried to readLines() a parquet file. This can happen if the check for parquet fails in L25 of process_chunks.R. Do you have `arrow` installed? 

Here's an example recreation of your error: 

```
library(arrow)
write_parquet(mtcars, "test.parquet")
readLines("test.parquet")

# this output is being cat to console
[1] "PAR1\025\004\025\x90\003\025\x88\002L\0252\025\004\022"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
[2] "\b\004\x99,"   
...
```

**Comment by GitHunter0** [comment]
Now that I upgraded `arrow` from version 9 to 10, everything seems to be working fine! Thanks a lot folks, @cboettig and @1beb
