### ISSUE TITLE
Different number of rows between the original table and the new imported one.

### ISSUE THREAD

**Issue by GitHunter0** [ropensci/arkdb#51]
Hi folks, first let me say that the functionality that `arkdb` provides is great and very much needed.

My issue is that I'm exporting a table via `ark()` but then when I create a new one using `unark()`, it has different number of rows.

This is my code (sorry that I could not share my data, it is restricted):
```
  arkdb::ark(
    db_con = db_con, 
    dir = '...', 
    tables = "original_table",
    filenames = NULL,
    overwrite = TRUE,
    lines=5e+5L
  )  
  files <- fs::dir_ls('...', glob="*.tsv.bz2") 

  arkdb::unark(
    files = files, 
    db_con = db_con, 
    tablenames = "new_imported_table",
    overwrite = TRUE,
    lines=5e+5L
  )
```
`original_table` has 798594 rows while `new_imported_table` has 797904 (missing a few).

Please, what are the possible reasons for that?

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

other attached packages:
[1] arkdb_0.0.15 DBI_1.1.2  
```

**Comment by cboettig** [comment]
Thanks for the kind words, I'm glad it's useful.  Can you see if you can reproduce this with a public dataset? You might find one of the large-ish datasets already packaged for R, like the {nycflights13} package, to be useful.  I'm afraid we can't help much without being able to reproduce the issue.

**Comment by GitHunter0** [comment]
Thank you @cboettig , I'm was actually able to reproduce the issue with the package you suggested. Here is code:
```
# db_con_local is my the connection with my local MySQL server.

table_name <- "test_original" 

DBI::dbWriteTable(db_con_local, table_name, nycflights13::flights, overwrite=TRUE)

arkdb::ark(
  db_con = db_con_local, 
  dir = ".", 
  tables = table_name,  
  filenames = NULL,
  overwrite = TRUE,
  lines=5e+5L
) 

files <- glue::glue("./{table_name}.tsv.bz2")

arkdb::unark(
  files = files, 
  db_con = db_con_local,
  tablenames = "test",
  overwrite = TRUE,
  lines=5e+5L
) 
```

Below are the pictures with the properties of both tables:
![image](https://user-images.githubusercontent.com/26294221/163233029-200ae3c5-fa7a-4a8f-9c1a-215c6af749d1.png)
![image](https://user-images.githubusercontent.com/26294221/163232998-b88b6208-5b05-403e-897d-a0b266c17bb7.png)

We can see that for some reason `test` table has fewer rows than `test_original`.

PS: I'm also having a problem to use `arkdb::unark()` to import the local file to a remote AWS RDS MySQL Database, it is taking a huge amount of time. I would like to open a separate issue about that if I may.
