### ISSUE TITLE
Importing the local .tsv.bz2 file via unark() to a remote AWS RDS MySQL Database is taking an unusual amount of time

### ISSUE THREAD

**Issue by GitHunter0** [ropensci/arkdb#52]
Hi folks,

Please, consider this MWE:
```
# db_con_local: connection to my local MySQL database
# db_con_remote: connection to my remote AWS RDS MySQL database

table_name <- "table_original" 

df <- nycflights13::flights

DBI::dbWriteTable(db_con_local, table_name, df, overwrite=TRUE)

arkdb::ark(
  db_con = db_con_local, 
  dir = "data", 
  tables = table_name,  
  filenames = NULL,
  overwrite = TRUE,
  lines=5e+5L
) 

files <- glue::glue("./{table_name}.tsv.bz2")

arkdb::unark(
  files = files, 
  db_con = db_con_remote,
  tablenames = "table_imported",
  overwrite = TRUE,
  lines=5e+5L
) 
```
Although the `.tsv.bz2` file in this case has just 5MB, the `unark()` command above takes **several hours** and still does not finish the task, until I'm forced to stop R.

I believe this issue is related to https://github.com/r-dbi/RMariaDB/issues/265 .

For some reason, loading data in a remote MySQL database is way faster using the SQL command ` LOAD DATA LOCAL INFILE`.

This alternative rotine for example only took a **few seconds**:
```
# db_con_remote: connection to my remote AWS RDS MySQL database

 table_name <- "test" 
  
  table_file_path <- glue::glue("data/{table_name}.csv") |> fs::path_abs()
  
  df <- nycflights13::flights
  
  data.table::fwrite(df, table_file_path)
  
  DBI::dbWriteTable(db_con_remote, table_name, df[1,], overwrite=TRUE)
  
  DBI::dbExecute(db_con_remote, glue::glue("TRUNCATE {table_name}"))

# Then run this query in MySQL Workbench (which took only 9 seconds):

        TRUNCATE <<table_name>>;
        LOAD DATA LOCAL INFILE '<<table_file_path>>' 
        INTO TABLE <<table_name>>
        CHARACTER SET utf8mb4 
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' 
        LINES  TERMINATED BY '\r\n'  
        IGNORE 1 LINES; 
```

Is there a solution for that?

Thank you

**Comment by cboettig** [comment]
I don't have an AWS RDS MySQL db handy to test unfortunately.  You might simplify things further by (a) testing with an uncompressed file and (b) testing with a trivially small dataset such that you can run `profvis()` or equivalent profiling to see where the slowest steps are.

It looks like you alternative method may not be entirely analogous though, it seems you are just writing `df[1,]` there?  

Also sounds like you suspect part of the issue is related specifically to RMariaDB -- is there a part that you think is specifically `arkdb`-related?  (`arkdb` really doesn't do much beyond just calling `dbWriteTable` in chunks; and this data is small enough to write in a single chunk, so like you I suspect the performance issue must be something specific to MariaDB or the R driver thereof.  Honestly I have almost never touched MySQL since discovering `duckdb` and `arrow`....).

**Comment by GitHunter0** [comment]
Thank you very much for your feedback, @cboettig .

Some very small datasets worked but way slower than `LOAD LOCAL DATA INFILE`.

I used `df[1,]` just to make a boilerplate for the table since `LOAD LOCAL DATA INFILE` requires a preexisting table.

I agree with you that the problem is probably solely related to RMariaDB , I will try to work the issue there.

**Comment by GitHunter0** [comment]
Hey @cboettig , https://github.com/r-dbi/RMariaDB/issues/265 was solved.
So I will just leave you a suggestion if I may.
Adding an option to use `LOAD LOCAL DATA INFILE` method as `unark()` backend would solve this freezing and slowness issue when dealing with remote MySQL databases.
Thank you

**Comment by cboettig** [comment]
Thanks for the heads up!  A PR to add this for MySQL-type remotes would be welcome.

**Comment by GitHunter0** [comment]
@cboettig, soon I will take a look in the inner workings of `arkdb` to see if I can do that, thank you!

**Comment by GitHunter0** [comment]
> @cboettig, soon I will take a look in the inner workings of `arkdb` to see if I can do that, thank you!

For what've seen the rightful solution would be to add `LOAD DATA LOCAL INFILE` method to `DBI::dbWriteTable()` backend, so I will discuss this possibility with the `DBI` contributors.

**Comment by cboettig** [comment]
makes total sense, thanks!

**Comment by GitHunter0** [comment]
`DBI::dbWriteTable()` is now using `LOAD DATA LOCAL INFILE` as a backend and working perfectly for remote MySQL databases, as discussed here https://github.com/r-dbi/RMariaDB/issues/265 .

And as I suspected, `arkdb` is now working flawlessly as well. The only requirement is to use this version `r-dbi/RMariaDB#267`, however they will probably soon merge to the main branch and upload to CRAN.

@cboettig , thanks again!

**Comment by cboettig** [comment]
awesome, thanks for reporting this!
